name: build-pydantic-android

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Rust + target
        run: |
          rustup target add aarch64-linux-android

      - name: Install build deps
        run: |
          pip install maturin
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Download source
        run: |
          pip download pydantic-core --no-binary=:all:
          ls

      - name: Build wheel
        run: |
          tar -xf pydantic_core-*.tar.gz
          cd pydantic_core-*
          maturin build --release --target aarch64-linux-android

      - name: Upload wheel
        uses: actions/upload-artifact@v4
        with:
          name: wheel
          path: pydantic_core-*/target/wheels/*.whl
